-- AlterTable
ALTER TABLE "clinicalTab" ALTER COLUMN "physician_first_name" DROP NOT NULL,
ALTER COLUMN "physician_last_name" DROP NOT NULL,
ALTER COLUMN "physician_phone" DROP NOT NULL,
ALTER COLUMN "pre_op_required" DROP NOT NULL,
ALTER COLUMN "pre_op_date_time" DROP NOT NULL,
ALTER COLUMN "show_pre_op_location" DROP NOT NULL,
ALTER COLUMN "pre_op_facility_name" DROP NOT NULL,
ALTER COLUMN "pre_op_phone" DROP NOT NULL,
ALTER COLUMN "pre_op_address_one" DROP NOT NULL,
ALTER COLUMN "pre_op_address_two" DROP NOT NULL,
ALTER COLUMN "pre_op_city" DROP NOT NULL,
ALTER COLUMN "pre_op_state" DROP NOT NULL,
ALTER COLUMN "pre_op_zip" DROP NOT NULL,
ALTER COLUMN "diagnostic_tests_required" DROP NOT NULL;
