import React, { useState } from "react";
import Head from "next/head";
import styles from "../styles/Home.module.css";
import { createTheme, ThemeProvider } from "@mui/material/styles";
import AppBar from "../components/appBar";
import SideBar from "../components/sideBar";
import StaticDatePicker from "../components/staticDatePicker";
import PatientTable from "../components/patientTable";
import TextField from "@mui/material/TextField";
import moment from "moment";

export default function Home() {
  const appBarTheme = createTheme({
    components: {
      MuiAppBar: {
        styleOverrides: {
          colorPrimary: {
            backgroundColor: "white",
          },
        },
      },
    },
  });

  const [proceduralist, setProceduralist] = useState("");
  const [procedureLocation, setProcedureLocation] = useState("");
  const [procedureDate, setProcedureDate] = useState(moment());

  return (
    <div className={styles.container}>
      <Head>
        {/* ensure styling for all device sizes (mobile, desktop etc.) */}
        <meta name="viewport" content="initial-scale=1, width=device-width" />
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header>
        <ThemeProvider theme={appBarTheme}>
          <AppBar></AppBar>
        </ThemeProvider>
        <SideBar></SideBar>
      </header>
      <main className={styles.main}>
        <StaticDatePicker
          setProcedureDate={setProcedureDate}
          procedureDate={procedureDate}
        ></StaticDatePicker>
        <TextField
          label="Enter Proceduralist"
          onChange={(event) => setProceduralist(event.target.value)}
          sx={{ marginBottom: 5 }}
        />
        <TextField
          label="Enter Procedure Location"
          onChange={(event) => setProcedureLocation(event.target.value)}
          sx={{ marginBottom: 5 }}
        />
        <PatientTable
          procedureDate={procedureDate.utc().format("MM-DD-YYYY")}
          proceduralist={proceduralist}
          procedureLocation={procedureLocation}
        ></PatientTable>
      </main>
    </div>
  );
}
