import Head from "next/head";
import styles from "../styles/Home.module.css";
import Button from "@mui/material/Button";
import Typography from "@mui/material/Typography";
import { createTheme, ThemeProvider } from "@mui/material/styles";
import AppBar from "../components/appBar";
import SideBar from "../components/sideBar";
import StaticDateRangePicker from "../components/staticDateRangePicker";

export default function Home() {
  const theme = createTheme({
    typography: {
      poster: {
        color: "primary.main",
      },
      h3: undefined,
    },
  });

  const appBarTheme = createTheme({
    components: {
      MuiAppBar: {
        styleOverrides: {
          colorPrimary: {
            backgroundColor: "white",
          },
        },
      },
    },
  });

  const mappingTheme = createTheme({
    typography: {
      fontSize: 10,
      fontFamily: "sans-serif",
    },
    components: {
      MuiTypography: {
        defaultProps: {
          variantMapping: {
            h3: "h2",
            h4: "h2",
          },
        },
      },
    },
  });

  return (
    <div className={styles.container}>
      <Head>
        {/* ensure styling for all device sizes (mobile, desktop etc.) */}
        <meta name="viewport" content="initial-scale=1, width=device-width" />
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header>
        <ThemeProvider theme={appBarTheme}>
          <AppBar></AppBar>
        </ThemeProvider>
        <SideBar></SideBar>
      </header>
      <main className={styles.main}>
        <StaticDateRangePicker></StaticDateRangePicker>
      </main>
    </div>
  );
}
