import React, { useState } from "react";
import moment from "moment";

import Head from "next/head";
import styles from "../styles/Home.module.css";
import Button from "@mui/material/Button";
import Typography from "@mui/material/Typography";
import { createTheme, ThemeProvider } from "@mui/material/styles";
import AppBar from "../components/appBar";
import SideBar from "../components/sideBar";
import StaticDatePicker from "../components/staticDatePicker";
import ResponsiveDatePicker from "../components/responsiveDatePicker";

export default function Home() {
  const mappingTheme = createTheme({
    typography: {
      fontSize: 10,
      fontFamily: "sans-serif", //overrides global fontFamily
    },
    components: {
      MuiTypography: {
        defaultProps: {
          variantMapping: {
            h3: "h2",
            h4: "h2",
          },
        },
      },
    },
  });

  const [procedureDate, setProcedureDate] = useState(moment());

  return (
    <div className={styles.container}>
      <Head>
        {/* ensure styling for all device sizes (mobile, desktop etc.) */}
        <meta name="viewport" content="initial-scale=1, width=device-width" />
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header>
        <AppBar></AppBar>
        <SideBar></SideBar>
      </header>
      <main className={styles.main}>
        <StaticDatePicker
          setProcedureDate={setProcedureDate}
          procedureDate={procedureDate}
        ></StaticDatePicker>
        <ResponsiveDatePicker></ResponsiveDatePicker>
        <Typography variant="h3" component="h1">
          h1 component with h3 variant
        </Typography>
        <Typography variant="poster">poster theme</Typography>
        <Button>Button</Button>
        <Button variant="contained">Hello World</Button>
        <ThemeProvider theme={mappingTheme}>
          <Typography variant="h3" color="blue">
            h3 mapped to h2
          </Typography>
          <Typography variant="h4">h4 variant mapped to h2</Typography>
        </ThemeProvider>
        <h1 className={styles.title}>Hello Hopper! test</h1>
      </main>
    </div>
  );
}
