import React, { useState, useEffect } from "react";
import moment from "moment";
import Head from "next/head";
import styles from "../styles/Home.module.css";
import Button from "@mui/material/Button";
import Typography from "@mui/material/Typography";
import { createTheme, ThemeProvider } from "@mui/material/styles";
import AppBar from "../components/appBar";
import SideBar from "../components/sideBar";
import StaticDatePicker from "../components/staticDatePicker";
import ResponsiveDatePicker from "../components/responsiveDatePicker";
import CaseCard from "../components/caseCard";

export default function Home() {
  const [rows, setRows] = useState([]);

  const fetchPatientData = async () => {
    const response = await fetch(`/api/getCases?`, {
      "Content-Type": "application/json",
      Accept: "application/json",
    });
    const rows = await response.json();
    setRows(rows);
  };

  useEffect(() => {
    fetchPatientData();
  }, []);

  return (
    <div className={styles.container}>
      <Head>
        {/* ensure styling for all device sizes (mobile, desktop etc.) */}
        <meta name="viewport" content="initial-scale=1, width=device-width" />
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header>
        <AppBar></AppBar>
        <SideBar></SideBar>
      </header>
      <main className={styles.main}>
        {rows.map((row) => {
          return <CaseCard key={row} row={row}></CaseCard>;
        })}
      </main>
    </div>
  );
}
