import React, { useState, useEffect } from "react";
import moment from "moment";
import Head from "next/head";
import styles from "../styles/Home.module.css";
import AppBar from "../components/appBar";
import SideBar from "../components/sideBar";
import CaseCard from "../components/caseCard";
import Typography from "@mui/material/Typography";
import { createTheme, ThemeProvider } from "@mui/material/styles";
import { withLDConsumer } from 'launchdarkly-react-client-sdk';

export function Home({ flags }) {
  const [rows, setRows] = useState([]);

  const params = new URLSearchParams({
    dateRangeStart: moment().utc(),
  });

  const fetchPatientData = async () => {
    const response = await fetch(`/api/getCases?${params}`, {
      "Content-Type": "application/json",
      Accept: "application/json",
    });
    const rows = await response.json();
    setRows(rows);
  };

  useEffect(() => {
    fetchPatientData();
  }, []);

  const titleTheme = createTheme({
    typography: {
      body1: {
        width: '95%',
        fontSize: '14px',
        marginLeft: '70px',
        fontFamily: "Inter",
        fontStyle: "italic",
        marginTop: '30px'
      }
    },
  });

  function displayRows() {
    const orderedKeys = Object.keys(rows).sort(function (a, b) {
      return moment(a).diff(moment(b));
    });

    let cards = [];
    orderedKeys.map((uniqueKey) => {
      for (const [key, value] of Object.entries(rows)) {
        if (uniqueKey === key) {
          cards.push(<ThemeProvider theme={titleTheme}><Typography>{key}</Typography></ThemeProvider>);
          value.map((row) => {
            cards.push(<CaseCard key={row.caseID} row={row}></CaseCard>);
          });
        }
      }
    });
    return cards;
  }

  return (
      <div className={styles.container}>
        <Head>
          {/* ensure styling for all device sizes (mobile, desktop etc.) */}
          <meta name="viewport" content="initial-scale=1, width=device-width" />
          <title>Create Next App</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <header>
          {
            flags.displayTopNav ? <AppBar /> : null
          }
          {
            flags.displaySideBar ? <SideBar /> : null
          }
        </header>
        <main className={styles.main}>
          {displayRows()}
        </main>
      </div>
  );
}

export default withLDConsumer()(Home);
