import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import Button from "@mui/material/Button";
import Typography from "@mui/material/Typography";
import { createTheme, ThemeProvider } from "@mui/material/styles";
import AppBar from "../components/appBar";
import SideBar from "../components/sideBar";
import StaticDatePicker from "../components/staticDatePicker";
import ResponsiveDatePicker from "../components/responsiveDatePicker";
import PatientTable from "../components/patientTable";

//BOX VS CONTAINER VS GRID
//GRID (MOST OBVIOUS USE, WHEN YOU WANT TO CREATE A GRID PATTERN WITH MULTIPLE ELEMENTS)
//BOX (SIMILAR TO CONTAINER BUT USE WHEN YOU WANT TO ADD SX STYLING TO IT)... basically just a div that is wrapped in the MUI properties (i.e. using sx mui stuff) and now has access to the MUI shorthands
//box is slower performance wise (by a tiny bit)
//CONTAINER (CENTERS CONTENT HORIZONTALLY, usually used in conjunction with a box if you want to center some divs/elements horizontally )

export default function Home() {
  // passed into a ThemeProvider... everything within themeprovider has these themes applied
  const theme = createTheme({
    typography: {
      poster: {
        color: "primary.main",
      },
      // Disable h3 variant i.e. don't apply default h3 props
      h3: undefined,
    },
  });

  const appBarTheme = createTheme({
    components: {
      MuiAppBar: {
        styleOverrides: {
          colorPrimary: {
            backgroundColor: "white",
          },
        },
      },
    },
  });
  //can add a marginTop to this to push it down, make it same height as appbar and works!
  const drawerTheme = createTheme({
    components: {
      MuiDrawer: {
        styleOverrides: {
          paper: {
            background: "blue",
            marginTop: 64,
          },
        },
      },
    },
  });

  const mappingTheme = createTheme({
    typography: {
      fontSize: 10,
      fontFamily: "sans-serif",
    },
    components: {
      MuiTypography: {
        defaultProps: {
          variantMapping: {
            h3: "h2",
            h4: "h2",
          },
        },
      },
    },
  });

  return (
    <div className={styles.container}>
      <Head>
        {/* ensure styling for all device sizes (mobile, desktop etc.) */}
        <meta name="viewport" content="initial-scale=1, width=device-width" />
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header>
        <ThemeProvider theme={appBarTheme}>
          <AppBar></AppBar>
        </ThemeProvider>
        <SideBar></SideBar>
      </header>
      <main className={styles.main}>
        <StaticDatePicker></StaticDatePicker>
        <ResponsiveDatePicker></ResponsiveDatePicker>
        <PatientTable></PatientTable>
        <ThemeProvider theme={theme}>
          {/*You can change the underlying element for a one-off situation with the component prop like below*/}
          <Typography variant="h3" component="h1">
            h1 component with h3 variant
          </Typography>
          <Typography variant="poster">poster theme</Typography>
          <Button>Button</Button>
        </ThemeProvider>
        <Button variant="contained">Hello World</Button>
        <ThemeProvider theme={mappingTheme}>
          <Typography variant="h3" color="blue">
            h3 mapped to h2
          </Typography>
          <Typography variant="h4">h4 variant mapped to h2</Typography>
        </ThemeProvider>
      </main>
    </div>
  );
}
