import React, { useState, useEffect } from "react";
import Head from "next/head";
import styles from "../styles/Home.module.css";
import AppBar from "../components/appBar";
import SideBar from "../components/sideBar";
import Dashboard from "./dashboard";
import * as LaunchDarkly from 'launchdarkly-react-client-sdk';
import { QueryClient, QueryClientProvider } from 'react-query';

interface Props {
  flags: {
    [key: string]: {
      data: boolean
    }
  }
}

const queryClient = new QueryClient();

export function Home({ flags }: Props) {
  return (
    <QueryClientProvider client={queryClient}>
      <div className={styles.container}>
        <Head>
          {/* ensure styling for all device sizes (mobile, desktop etc.) */}
          <meta name="viewport" content="initial-scale=1, width=device-width" />
          <title>Create Next App</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <header>
          {
            flags.displayTopNav ? <AppBar /> : null
          }
          {
            flags.displaySideBar ? <SideBar /> : null
          }
        </header>
        <Dashboard />
      </div>
    </QueryClientProvider>
  );
}

export default LaunchDarkly.withLDConsumer()(Home);
